/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BottomNav: typeof import('./src/components/layouts/BottomNav.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    ControlOptions: typeof import('./src/components/SettingItems/ControlOptions.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DesktopLayout: typeof import('./src/components/layouts/DesktopLayout.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DisasterTable: typeof import('./src/components/disaster/DisasterTable.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Editor: typeof import('primevue/editor')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MapOptions: typeof import('./src/components/SettingItems/MapOptions.vue')['default']
    MarkerOptions: typeof import('./src/components/SettingItems/MarkerOptions.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MobileLayout: typeof import('./src/components/layouts/MobileLayout.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    PredictCard: typeof import('./src/components/home/PredictCard.vue')['default']
    RecommendCard: typeof import('./src/components/home/RecommendCard.vue')['default']
    RootLayout: typeof import('./src/components/layouts/RootLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Setting: typeof import('./src/components/TianDiTu/Setting.vue')['default']
    SixCard: typeof import('./src/components/home/SixCard.vue')['default']
    SunChart: typeof import('./src/components/home/SunChart.vue')['default']
    TianDiTu: typeof import('./src/components/TianDiTu/TianDiTu.vue')['default']
    Timeline: typeof import('primevue/timeline')['default']
    TopNav: typeof import('./src/components/layouts/TopNav.vue')['default']
    WeatherCard: typeof import('./src/components/home/WeatherCard.vue')['default']
  }
}
